### ISSUE TITLE
Jump to specific tab from other viewcontroller 

### ISSUE THREAD

**Issue by keyur158** [Abedalkareem/AMTabView#3]
Can you please help us that how to open on index 1 or 2 or any other specific tab from view controller.

**Comment by Abedalkareem** [comment]
Hi,
You can do that by changing the ```selectedTabIndex```.

```
  override func viewDidLoad() {
    super.viewDidLoad()

    setTabsControllers()

    selectedTabIndex = 2
  }
```

Thank you.
